[build-system]
# These are the assumed default build requirements from pip:
# https://pip.pypa.io/en/stable/reference/pip/#pep-517-and-518-support
requires = ["setuptools>=39.2.0", "wheel"]
build-backend = "setuptools.build_meta"
